#!/usr/bin/env bash

set -e

[[ -n $DOTFILES ]] || {
  printf "[ERROR] \$DOTFILES is not set!\n\n"
  printf "Example: DOTFILES=\$HOME/.dotfiles %s\n\n" "$0"
  exit 1
}

# Install homebrew. This will also install the Xcode Command Line Tools if they are not already installed.
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
brew analytics off

# Install oh-my-zsh. By setting $ZSH the installer use it for the installation path.
export ZSH="$DOTFILES/oh-my-zsh"
/bin/bash -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

# Ruby \o/
# Install chruby, ruby-install and install ruby version defined
# in $DOTFILES/etc/ruby-version.
brew install chruby ruby-install
ruby-install ruby $(cat "$DOTFILES/etc/ruby-version") -- --disable-install-rdoc --with-openssl-dir=$(brew --prefix openssl@1.1)

mkdir -p ~/.aws/

# misc
touch ~/.hushlogin

# FIXME: This will require "Full Disk Access privileges" :(
# TODO: Add tmutil isexcluded checks for each path
# NOTES:
# * to read excluded paths, shown in the UI, you can use:
#   defaults read /Library/Preferences/com.apple.TimeMachine SkipPaths
#   or defaults read /Library/Preferences/com.apple.TimeMachine SkipPaths | plutil -convert json -o - - | jq .
# * there is also an attribute that excludes items from TimeMachine, you can use this
#   to find them:
#   sudo mdfind "com_apple_backup_excludeItem = 'com.apple.backupd'"
sudo tmutil addexclusion -p "$(brew --prefix)"

sudo tmutil addexclusion -p ~/.rvm
sudo tmutil addexclusion -p ~/.rubies
sudo tmutil addexclusion -p ~/.gem

sudo tmutil addexclusion -p ~/.orbstack
sudo tmutil addexclusion -p ~/.tart
sudo tmutil addexclusion -p ~/Library/Containers/com.docker.docker

"$DOTFILES"/utils/bootstrap-link
