#!/usr/bin/env bash

set -e

[[ -n $DOTFILES ]] || {
  printf "[ERROR] \$DOTFILES is not set!\n\n"
  printf "Example: DOTFILES=\$HOME/.dotfiles %s\n\n" "$0"
  exit 1
}

# Install homebrew. This will also install the Xcode Command Line Tools if they are not already installed.
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
brew analytics off

# Install oh-my-zsh. By setting $ZSH the installer use it for the installation path.
export ZSH="$DOTFILES/oh-my-zsh"
/bin/bash -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

# Ruby \o/
"$DOTFILES"/utils/install-ruby

mkdir -p ~/.aws/

# misc
touch ~/.hushlogin

"$DOTFILES"/utils/tm-ignore
"$DOTFILES"/utils/bootstrap-link

ln -s "$(brew --prefix)/bin/yt-dlp" "$(brew --prefix)/bin/youtube-dl"
