#!/usr/bin/env bash

set -e

[[ -n $DOTFILES ]] || {
  printf "[ERROR] \$DOTFILES is not set!\n\n"
  printf "Example: DOTFILES=\$HOME/.dotfiles %s\n\n" "$0"
  exit 1
}

# Install homebrew. This will also install the Xcode Command Line Tools if they are not already installed.
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

# Install oh-my-zsh. By setting $ZSH the installer use it for the installation path.
export ZSH="$DOTFILES/oh-my-zsh"
/bin/bash -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

# Get RVM installed.
curl -sSL https://get.rvm.io | bash -s stable

mkdir -p ~/.aws/

# misc
touch ~/.hushlogin

"$DOTFILES"/utils/bootstrap-link

# install ZSH plugins
git clone https://github.com/zsh-users/zsh-syntax-highlighting.git "${ZSH_CUSTOM:-~/.oh-my-zsh/custom}"/plugins/zsh-syntax-highlighting
git clone https://github.com/zsh-users/zsh-autosuggestions "${ZSH_CUSTOM:-~/.oh-my-zsh/custom}"/plugins/zsh-autosuggestions
git clone https://github.com/zsh-users/zsh-completions.git "${ZSH_CUSTOM:-~/.oh-my-zsh/custom}"/plugins/zsh-completions
