#!/usr/bin/env bash

set -e

[[ -n $DOTFILES ]] || {
  echo "[ERROR] \$DOTFILES is not set"
  exit 1
}

ln -nfs "$DOTFILES/etc/ruby-version" ~/.ruby-version

ln -nfs "$DOTFILES/etc/zshrc" ~/.zshrc

ln -nfs "$DOTFILES/etc/ssh-config" ~/.ssh/config

# aws
ln -nfs "$DOTFILES/secrets/aws_credentials" ~/.aws/credentials

# irb & gem
ln -nfs "$DOTFILES/etc/irbrc" ~/.irbrc
ln -nfs "$DOTFILES/etc/gemrc" ~/.gemrc

# git
ln -nfs "$DOTFILES/etc/gitconfig" ~/.gitconfig

# other

mkdir -p ~/.yt-dlp
ln -nfs "$DOTFILES/etc/yt-dlp.conf" ~/.yt-dlp/config
