#!/usr/bin/env bash

set -e

AUDIT_SERVER_PORT=${PORT:-2222}

echo "Starting SSH audit server on $AUDIT_SERVER_PORT"
echo "In a different session, use"
echo
echo "    ssh -p $AUDIT_SERVER_PORT localhost"
echo
echo "to connect and see the audit results here"
echo

docker run --rm -t -p "$AUDIT_SERVER_PORT:2222" positronsecurity/ssh-audit --timeout 10 --client-audit
