on: push

name: "ShellCheck"

jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run ShellCheck  (./bin)
      uses: ludeeus/action-shellcheck@v2
      env:
        SHELLCHECK_OPTS: -e SC1071
      with:
       scandir: "./bin"
    - name: Run ShellCheck (./utils)
      uses: ludeeus/action-shellcheck@v2
      with:
       scandir: "./utils"
